# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sanity-inventory-sync-app"
client_id = "8d2818f24c813453a8b9e7bb3f3f50ca"
application_url = "https://neutral-surfaces-experiences-excuse.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_gift_cards, read_inventory, write_inventory, write_gift_cards, read_locations, write_locations, read_products, write_products, read_shipping, write_shipping"

[auth]
redirect_urls = [
  "https://neutral-surfaces-experiences-excuse.trycloudflare.com/auth/callback",
  "https://neutral-surfaces-experiences-excuse.trycloudflare.com/auth/shopify/callback",
  "https://neutral-surfaces-experiences-excuse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "inventory-location-test-store.myshopify.com"
